[theme]
primaryColor = "#3F88E8"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 5
enableCORS = true

[browser]
gatherUsageStats = false 